### ISSUE TITLE
On test mode, OTP is not sent to customer's phone

### ISSUE THREAD

**Issue by nshutijean** [Flutterwave/Flutterwave-Vue-v3#1]
As an example, php/laravel's SDK sends successfully OTP to customer's phone number on a test mode, but not in Vue SDK. Unless if a user or I already know that it's 123456, it wont be possible to know. 

Regardless, on a live mode, it works swiftly👌🏽

**Comment by toybz** [comment]
Hello @nshutijean 
This is not an issue. On Test mode, we provide pre defined OTP codes to make the testing process easier.
Please check [here](https://developer.flutterwave.com/docs/test-cards)  for the Pre defined codes.

**Comment by nshutijean** [comment]
Thanks for your response. Sorry i forgot to say that i was testing on mobile money and if it persists i will let you know
