### ISSUE TITLE
Customer details not binding to input fields

### ISSUE THREAD

**Issue by vinosamari** [Flutterwave/Flutterwave-Vue-v3#11]
I keep getting an invalid email error on the modal every time I bind the customer name, email, and phone number fields to the v-model on the input fields to programmatically populate those fields. The same goes for the amount stating that it must not be less than zero. Using console log statements to debug indicates that all fields are returning expected values. Help! 
I'm using Vue/Nuxt 2.x 
I basically need to not hardcode the customer details.

**Comment by toybz** [comment]
Hello @vinosamari 

This issue will most likely be because the updated value is not passed to the SDK.

Please can you share your payment component?

NB: Please use dummy values for any sensitive data like mobile number, email, API Keys, etc.

**Comment by toybz** [comment]
Hello @vinosamari 

Thank you for sharing.

Please move the paymentData out of the Data prop, and set it as a computed property instead.
Please see the updated code below:

 data() {
  return {
    customerName: "",
    customerEmail: "",
    customerPhone: "",
    checkedOut: false,
    cartCount: this.$store.state.cartCount,
    orderTotal: this.$store.state.orderTotal,
    orders: this.$store.state.cart,
   
}
},

computed: {

paymentData(){
return {
      tx_ref: this.generateReference(),
      amount: this.orderTotal,
      currency: "GHS",
      payment_options: "card,ussd,mobilemoney",
      redirect_url: "https://lumenbarandgrill.com/success",
      customer: {
        name: this.customerName,
        email: this.customerEmail,
        phone_number: this.customerPhone,
      },
      customizations: {
        title: "Lumen Bar & Grill",
        description: "Online order payment",
        logo: "https://flutterwave.com/images/logo-colored.svg",
      },
      callback: this.makePaymentCallback,
      onclose: this.closedPaymentModal,
    }
}
  }

Please try this and let me know if it works, best regards

**Comment by vinosamari** [comment]
@toybz Will do right away. Thanks again.
