### ISSUE TITLE
redirect_url returning ‘server not found’

### ISSUE THREAD

**Issue by vinosamari** [Flutterwave/Flutterwave-Vue-v3#12]
Correct me if I'm wrong but I thought the redirect_url property was for the link to the page on your site that handles success or failure of a transaction depending on the status query param. I set mine to the page on the site waiting to handle the query params but I keep getting a server not found error. What am I doing wrong?

**Comment by toybz** [comment]
Hello @vinosamari 

Apologies for the late response.

Please share a screenshot of the redirect page showing the error.

**Comment by vinosamari** [comment]
No problem @toybz i figured out the issue and to be honest it made me get a broader understanding of debugging Vue/Nuxt. I'm trying to use the web hook to verify transactions and I'm using Cloudflare workers for that. I'm still on it but so far it's all good.

**Comment by toybz** [comment]
Happy to hear this @vinosamari

**Comment by vinosamari** [comment]
One more thing @toybz. Can I set the value of the redirect_url properly to an environment variable(process.env.FLW_REDIRECT_ITL) so that I can test the whole user flow in development easily. The present value is a hard-coded link to the appropriate url(example.com/verify-transaction)on the site.

**Comment by toybz** [comment]
Hello @vinosamari 
Yes, you can set it using deployment variables
