### ISSUE TITLE
Can't close Modal with method

### ISSUE THREAD

**Issue by temitopeadesoji** [Flutterwave/Flutterwave-Vue-v3#2]
The method closePaymentModal() does not close the modal

**Comment by temitopeadesoji** [comment]
TypeError: _this2.asyncPayWithFlutterwave is not a function 
same error I got when the asyncPayWithFlutterwave method is called.

I am using NuxtJS

**Plugin**
import Vue from 'vue'
import Flutterwave from 'flutterwave-vue-v3'

Vue.use(Flutterwave, {
  publicKey: 'FLWPUBK_TEST-XXXXXXXXXXXXXXX',
})

**Nuxt config**
{ src: '~/plugins/rave', mode: 'client' }

**Comment by toybz** [comment]
Hello @temitopeadesoji .
Thank you for your feedback.
We will look into this issues and amend them as soon as possible.

Best regards.

**Comment by Douglasokolaa** [comment]
@toybz  any update with this issue?

I also get this error.
```

    "devDependencies": {
        "@inertiajs/inertia": "^0.3.0",
        "@inertiajs/inertia-vue": "^0.2.0",
        "@tailwindcss/ui": "^0.6.0",
        "axios": "^0.19",
        "cross-env": "^7.0",
        "laravel-jetstream": "^0.0.3",
        "laravel-mix": "^5.0.1",
        "lodash": "^4.17.19",
        "moment": "^2.26.0",
        "portal-vue": "^2.1.7",
        "postcss-import": "^12.0.1",
        "resolve-url-loader": "^3.1.0",
        "tailwindcss": "^1.8.0",
        "vue": "^2.5.17",
        "vue-template-compiler": "^2.6.10"
    },
    "dependencies": {
        "@inertiajs/progress": "^0.1.1",
        "flutterwave-vue-v3": "^1.0.2",
        "vue-dropify": "^0.4.1",
        "vue-select": "^3.11.2",
        "vue-tel-input": "^4.4.2",
        "vue2-dropzone": "^3.6.0"
    }
```

**Comment by toybz** [comment]
Hello  @temiadesina, Hello @Douglasokolaa 

Issue is now resolved.
Please update to the latest version of the SDK.

Best regards.
